# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleCommon', '0006_auto_20170920_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='value',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
