# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleCommon', '0007_auto_20170920_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
