# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleCommon', '0008_auto_20170920_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='periodo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
