# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModuleCommon', '0010_auto_20170925_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attorney',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
